export const FETCH_TRENDING = 'FETCH_TRENDING';
export const RECEIVE_TRENDING = 'RECEIVE_TRENDING';
export const FETCH_GIF_QUERY = 'FETCH_GIF_QUERY';
export const FETCH_FAVORITES = 'FETCH_FAVORITES';
export const FETCH_DETAILS = 'FETCH_DETAILS';